=begin
#==============================================================================#
# Neo Wonder-Trading ~By PDM20, Original by Black Eternity                     #
#==============================================================================#
RandTN = [
"Aaron","Adam","Albert","Alex","Alexa","Alexandra","Ali","Alice","Amber","Amy","Andrea",										
"Andrew","Anne","Annie","Anthony","Ariel","Arthur","Ashley","Aurora","Ben","Betty","Beverly",										
"Bill","Blake","Bobby","Brandon","Brian","Brigitte","Bruno","Carl","Carolyn","Catherine","Charles",										
"Cheryl","Chloe","Christina","Christine","Christopher","Clarence","Cody","Craig","Darren","David","Deborah",										
"Denise","Dennis","Diane","Divya","Donald","Donna","Dorist","Dorothy","Douglas","Ella","Elsa",										
"Emily","Ernest","Evelyn","Farah","Fiona","Frances","Fred","Galen","Gary","Geeta","George",										
"Gita","Grace","Greg","Harold","Harry","Helen","Henrietta","Henry","Howard","Irene","Jack",										
"Jacqueline","James","Janice","Jasmine","Jayesh","Jean","Jeffrey","Jeremy","Jesse","Joan","Joe",										
"Joel","Joseph","Josh","Juan","Julia","Kaitlyn","Karen","Karina","Karthik","Katherine","Kathleen",										
"Kathryn","Kathy","Katie","Keith","Kenneth","Kevin","Larry","Laura","Linda","Lisa","Lois",										
"Lori","Lorraine","Louis","Louisel","Luc","Luke","Maria","Marie","Marina","Marissa","Martin",										
"Matt","Matthew","Melissa","Merlyn","Michael","Michelle","Mildred","Nancy","Nathan","Nerissa","Ophelia",										
"Patricia","Patrick","Paul","Peter","Phillip","Phyllis","Rachaita","Rachel","Raj","Ralph","Randy",										
"Raymond","Rhea","Rick","Roger","Ronald","Rose","Rowan","Russell","Sandra","Sara","Scott",										
"Sean","Shae","Sharon","Shirley","Shoban","Spencer","Stephanie","Stephen","Steve","Steven","Susan",										
"Tara","Taylor","Ted","Teresa","Theresa","Tia","Todd","Tyler","Tyson","Vanessa","Victoria",										
"Virginia","Wanda","Wesley","Weston","William","Zoey"]

RandPN = [
"Ami","Amore","Anvil","Ash","Bambam","Babs","Backbone","Baldie","Bambino","Bandit","Beetle","Big",
"Boomhauer","Braveheart","Brown","Bubble","Bumpkin","BunnyRabbit","Butt","Captain","Carrot","Cheddar","Chewbacca",
"Coach","Coke","Conductor","Crunch","Cyber","Dear","Dingo","Doctor","Dolly","Doofus","Double","Dracula",
"Dragon","Dragonfly","Drake","Dropout","Dulce","Fiesta","Foxy","Frauline","Frogger","Genius","Giant",
"Goblin","Goose","Green","Heisenberg","Jackrabbit","Jet","Kitten","Kitty","Lobster","MacLady","Mama",
"Matey","MissPiggy","Mistress","Mouse","Munchkin","Nocturnal","Oreo","PBJ","Pearl","Pebbles","Pepper","Pinata","Psycho","Punk",
"QueenBee","Rockette","Rosebud","Shuttershy","SickleCell","Silly","Slim","Sugar","Sunny","Tater","Tots","Turkey",
"Turtle","Twig","Twiggy","Wheels","Wilma","Yammer","Zak","Zeke"]

RandPkmn = [:KOFFING,:WEEZING,:SOLOSIS,:DUOSION,:REUNICLUS,:GASTLY,:HAUNTER,:GENGAR,:DODUO,:DODRIO,:EKANS,:ARBOK,:STARYU,:STARMIE,:ONIX,:STEELIX,:SLUGMA,:MAGCARGO,:WAILMER,:WAILORD,:FLETCHLING,:FLETCHINDER,:TALONFLAME,:NATU,:XATU,:RUFFLET,:BRAVIARY,:NOSEPASS,:PROBOPASS,:ZUBAT,:GOLBAT,:CROBAT,:TANGELA,:TANGROWTH,:TYMPOLE,:PALPITOAD,:SEISMITOAD,:GULPIN,:SWALOT,:SPINARAK,:ARIADOS,:BALTOY,:CLAYDOL,:ZORUA,:ZOROARK,:DUCKLETT,:SWANNA,:GOLETT,:GOLURK,:MORELULL,:SHIINOTIC,:LARVESTA,:VOLCARONA,:STANTLER,:MAGIKARP,:GYARADOS,:BERGMITE,:AVALUGG,:LEDYBA,:LEDIAN,:PONYTA,:RAPIDASH,:AMAURA,:AURORUS,:GEODUDE,:GRAVELER,:GOLEM,:SKRELP,:DRAGALGE,:LITLEO,:PYROAR,:LUNATONE,:SOLROCK,:DROWZEE,:HYPNO,:SEEL,:DEWGONG,:SKIDDO,:GOGOAT,:KABUTO,:KABUTOPS,:SHROOMISH,:BRELOOM,:AERODACTYL,:ROGGENROLA,:BOLDORE,:GIGALITH,:FINNEON,:LUMINEON,:GLIGAR,:GLISCOR,:LILLIPUP,:HERDIER,:STOUTLAND,:DRIFLOON,:DRIFBLIM,:MINCCINO,:CINCCINO,:BONSLY,:SUDOWOODO,:DRUDDIGON,:WOOBAT,:SWOOBAT,:KRABBY,:KINGLER,:HOOTHOOT,:NOCTOWL,:VOLTORB,:ELECTRODE,:SANDYGAST,:PALOSSAND,:WEEDLE,:KAKUNA,:BEEDRILL,:MACHOP,:MACHOKE,:MACHAMP,:BULBASAUR,:IVYSAUR,:VENUSAUR,:TAUROS,:CARVANHA,:SHARPEDO,:TIMBURR,:GURDURR,:CONKELDURR,:LITWICK,:LAMPENT,:CHANDELURE,:VANILLITE,:VANILLISH,:VANILLUXE,:ELEKID,:ELECTABUZZ,:ELECTIVIRE,:POPPLIO,:BRIONNE,:PRIMARINA,:SNORUNT,:GLALIE,:FROSLASS,:MAGBY,:MAGMAR,:MAGMORTAR,:EXEGGCUTE,:EXEGGUTOR,:JOLTIK,:GALVANTULA,:GRIMER,:MUK,:CHIMCHAR,:MONFERNO,:INFERNAPE,:SABLEYE,:CUBCHOO,:BEARTIC,:TREECKO,:GROVYLE,:SCEPTILE,:LARVITAR,:PUPITAR,:TYRANITAR,:HIPPOPOTAS,:HIPPOWDON,:BRONZOR,:BRONZONG,:SWIRLIX,:SLURPUFF,:MAREEP,:FLAAFFY,:AMPHAROS,:SWABLU,:ALTARIA,:ABRA,:KADABRA,:ALAKAZAM,:VENIPEDE,:WHIRLIPEDE,:SCOLIPEDE,:HERACROSS,:TEDDIURSA,:URSARING,:PSYDUCK,:GOLDUCK,:DUSKULL,:DUSCLOPS,:DUSKNOIR,:SKITTY,:DELCATTY,:EEVEE2,:VAPOREON,:JOLTEON,:FLAREON,:ESPEON,:UMBREON,:LEAFEON,:GLACEON,:SYLVEON,:DEERLING,:SAWSBUCK,:ARON,:LAIRON,:AGGRON,:SHELLOS,:GASTRODON,:SHELLOS_1,:GASTRODON_1,:SHELLOS_2,:GASTRODON_2,:SHELLOS_3,:GASTRODON_3,:SHELLOS_4,:GASTRODON_4,:SHELLOS_5,:GASTRODON_5,:SHELLOS_6,:GASTRODON_6,:SHELLOS_7,:GASTRODON_7,:SHELLOS_8,:GASTRODON_8,:SHELLOS_9,:GASTRODON_9,:SHELLOS_10,:GASTRODON_10,:SHELLOS_11,:GASTRODON_11,:MEOWTH,:PERSIAN,:WURMPLE,:SILCOON,:BEAUTIFLY,:WURMPLE2,:CASCOON,:DUSTOX,:AIPOM,:AMBIPOM,:RATTATA,:RATICATE,:STARLY,:STARAVIA,:STARAPTOR,:KRICKETOT,:KRICKETUNE,:SLOWPOKE,:SLOWBRO,:SLOWKING,:ROOKIDEE,:CORVISQUIRE,:CORVIKNIGHT,:ODDISH,:GLOOM,:VILEPLUME,:BELLOSSOM,:SUNKERN,:SUNFLORA,:STUNKY,:SKUNTANK,:FEEBAS,:MILOTIC,:HORSEA,:SEADRA,:KINGDRA,:YAMPER,:BOLTUND,:VENONAT,:VENOMOTH,:CATERPIE,:METAPOD,:BUTTERFREE,:MANKEY,:PRIMEAPE,:TYNAMO,:EELEKTRIK,:EELEKTROSS,:EEVEE,:GALAXEON,:PRISMEON,:OCTAVEON,:BASCULIN,:BASCULIN_1,:CHINCHOU,:LANTURN,:NOIBAT,:NOIVERN,:PARAS,:PARASECT,:IMPIDIMP,:MORGREM,:GRIMMSNARL,:PIDOVE,:TRANQUILL,:UNFEZANT,:UNFEZANT,:SEEDOT,:NUZLEAF,:SHIFTRY,:HOPPIP,:SKIPLOOM,:JUMPLUFF,:DWEBBLE,:CRUSTLE,:SENTRET,:FURRET,:CHIKORITA,:BAYLEEF,:MEGANIUM,:CYNDAQUIL,:QUILAVA,:TYPHLOSION,:RALTS,:KIRLIA,:GARDEVOIR,:GALLADE,:NUMEL,:CAMERUPT,:LAPRAS,:TOTODILE,:CROCONAW,:FERALIGATR,:DIGLETT,:DUGTRIO,:CROAGUNK,:TOXICROAK,:SPRITZEE,:AROMATISSE,:DURANT,:YANMA,:YANMEGA,:AZURILL,:MARILL,:AZUMARILL,:COMFEY,:ROWLET,:DARTRIX,:DECIDUEYE,:SKORUPI,:DRAPION,:FURFROU,:FURFROU_1,:FURFROU_2,:FURFROU_3,:FURFROU_4,:FURFROU_5,:FURFROU_6,:MELOETTA,:POOCHYENA,:MIGHTYENA,:LITTEN,:TORRACAT,:INCINEROAR,:SPIRITOMB,:ABSOL,:HONEDGE,:DOUBLADE,:AEGISLASH,:HONEDGE_1,:DOUBLADE_1,:AEGISLASH_1,:HONEDGE_2,:DOUBLADE_2,:AEGISLASH_2,:HONEDGE_3,:DOUBLADE_3,:AEGISLASH_3,:BELDUM,:METANG,:METAGROSS,:DUNSPARCE,:MEDITITE,:MEDICHAM,:NINCADA,:NINJASK,:SHEDINJA,:DEINO,:ZWEILOUS,:HYDREIGON,:CHERUBI,:CHERRIM_1,:CHERRIM,:GOSSIFLEUR,:ELDEGOSS,:ESPURR,:MEOWSTIC,:ESPURR_1,:MEOWSTIC_1,:CORSOLA,:CURSOLA,:PIDGEY,:PIDGEOTTO,:PIDGEOT,:MANTYKE,:MANTINE,:LILEEP,:CRADILY,:MURKROW,:HONCHKROW,:CACNEA,:CACTURNE,:HAPPINY,:CHANSEY,:BLISSEY,:TENTACOOL,:TENTACRUEL,:BOUNSWEET,:STEENEE,:TSAREENA,:GROWLITHE,:ARCANINE,:ELGYEM,:BEHEEYEM,:SILICOBRA,:SANDACONDA,:PICHU,:PIKACHU,:RAICHU,:YAMASK,:COFAGRIGUS,:SINISTEA,:POLTEAGEIST,:THROH,:SAWK,:SANDILE,:KROKOROK,:KROOKODILE,:MUDKIP,:MARSHTOMP,:SWAMPERT,:GOLDEEN,:SEAKING,:TAILLOW,:SWELLOW,:PATRAT,:WATCHOG,:GOTHITA,:GOTHORITA,:GOTHITELLE,:SPHEAL,:SEALEO,:WALREIN,:SURSKIT,:MASQUERAIN,:WINGULL,:PELIPPER,:CHARMANDER,:CHARMELEON,:CHARIZARD,:MAGNEMITE,:MAGNETON,:MAGNEZONE,:SPEAROW,:FEAROW,:IGGLYBUFF,:JIGGLYPUFF,:WIGGLYTUFF,:VULLABY,:MANDIBUZZ,:SHINX,:LUXIO,:LUXRAY,:ELECTRIKE,:MANECTRIC,:FERROSEED,:FERROTHORN,:MAREANIE,:TOXAPEX,:SWINUB,:PILOSWINE,:MAMOSWINE,:TORKOAL,:TURTWIG,:GROTLE,:TORTERRA,:BUNEARY,:LOPUNNY,:BUIZEL,:FLOATZEL,:BUDEW,:ROSELIA,:ROSERADE,:KLEFKI,:DEWPIDER,:ARAQUANID,:GOTHITA2,:GOTHORITA2,:GOTHITELLE2,:TYRUNT,:TYRANTRUM,:CUBONE,:MAROWAK,:SPRITZEE2,:AROMATISSE2,:HORSEA2,:SEADRA2,:KINGDRA2,:CUTIEFLY,:RIBOMBEE,:OMANYTE,:OMASTAR,:SKWOVET,:GREEDENT,:GRIMER2,:MUK2,:PHANPY,:DONPHAN,:PIKIPEK,:TRUMBEAK,:TOUCANNON,:PINECO,:FORRETRESS,:HOOTHOOT2,:NOCTOWL2,:STUFFUL,:BEWEAR,:CARBINK,:GIBLE,:GABITE,:GARCHOMP,:VULPIX,:NINETALES,:BOUNSWEET2,:STEENEE2,:TSAREENA2,:PURRLOIN,:LIEPARD,:TOXEL,:TOXTRICITY,:DEWPIDER2,:ARAQUANID2,:GOOMY,:SLIGGOO,:GOODRA,:MIMEJR,:MRMIME,:MRRIME,:DIGLETT2,:DUGTRIO2,:LUVDISC,:SMEARGLE,:SHIELDON,:BASTIODON,:APPLIN,:FLAPPLE,:APPLETUN,:MIMIKYU,:WOOLOO,:DUBWOOL,:ABSOL2,:SNIVY,:SERVINE,:SERPERIOR,:FENNEKIN,:BRAIXEN,:DELPHOX,:VOLTORB2,:ELECTRODE2,:SNOVER,:ABOMASNOW,:EXEGGCUTE2,:EXEGGUTOR2,:SABLEYE2,:TRUBBISH,:GARBODOR,:SWABLU2,:ALTARIA2,:SLUGMA2,:MAGCARGO2,:MUDKIP2,:MARSHTOMP2,:SWAMPERT2,:CHESPIN,:QUILLADIN,:CHESNAUGHT,:FROAKIE,:FROGADIER,:GRENINJA,:JANGMOO,:HAKAMOO,:KOMMOO,:SCRAGGY,:SCRAFTY,:CHIKORITA2,:BAYLEEF2,:MEGANIUM2,:CYNDAQUIL2,:QUILAVA2,:TYPHLOSION2,:TOTODILE2,:CROCONAW2,:FERALIGATR2,:SURSKIT2,:MASQUERAIN2,:STANTLER2,:CLAMPERL,:HUNTAIL,:GOREBYSS,:KLINK,:KLANG,:KLINKLANG,:DARUMAKA,:DARMANITAN,:DARMANITAN_1,:SKITTY2,:DELCATTY2,:DODUO2,:DODRIO2,:NUMEL2,:CAMERUPT2,:BINACLE,:BARBARACLE,:ARROKUDA,:BARRASKEWDA,:MACHOP2,:MACHOKE2,:MACHAMP2,:FALINKS,:SMOOCHUM,:JYNX,:ZIGZAGOON,:LINOONE,:OBSTAGOON,:INDEEDEE,:CRANIDOS,:RAMPARDOS,:GIBLE2,:GABITE2,:GARCHOMP2,:YANMA2,:YANMEGA2,:EISCUE,:MISDREAVUS,:MISMAGIUS,:POLIWAG,:POLIWHIRL,:POLIWRATH,:POLITOED,:PHANTUMP,:TREVENANT,:TYROGUE,:HITMONLEE,:HITMONCHAN,:HITMONTOP,:PINCURCHIN,:SCYTHER,:SCIZOR,:PINSIR,:ROLYCOLY,:CARKOL,:COALOSSAL,:RIOLU,:LUCARIO,:TRAPINCH,:VIBRAVA,:FLYGON,:DHELMISE,:GEODUDE2,:GRAVELER2,:GOLEM2,:ROGGENROLA2,:BOLDORE2,:GIGALITH2,:VANILLITE2,:VANILLISH2,:VANILLUXE2,:DRATINI,:DRAGONAIR,:DRAGONITE,:MURKROW2,:HONCHKROW2,:CLEFFA,:CLEFAIRY,:CLEFABLE,:KABUTO2,:KABUTOPS2,:ARCHEN,:ARCHEOPS,:TIRTOUGA,:CARRACOSTA,:DREEPY,:DRAKLOAK,:DRAGAPULT,:WIMPOD,:GOLISOPOD,:MUNNA,:MUSHARNA,:SHUPPET,:BANETTE,:STONJOURNER,:LAPRAS2,:WOOLOO2,:DUBWOOL2,:BIDOOF,:BIBAREL,:DRILBUR,:EXCADRILL,:DRILBUR2,:EXCADRILL2,:SNOM,:FROSMOTH,:HOUNDOUR,:HOUNDOOM,:PIPLUP,:PRINPLUP,:EMPOLEON,:SOLOSIS2,:DUOSION2,:REUNICLUS2,:MUDBRAY,:MUDSDALE,:CRAMORANT,:HOPPIP2,:SKIPLOOM2,:JUMPLUFF2,:SEWADDLE,:SWADLOON,:LEAVANNY,:WHISMUR,:LOUDRED,:EXPLOUD,:SIZZLIPEDE,:CENTISKORCH,:SOBBLE,:DRIZZILE,:INTELEON,:TIMBURR2,:GURDURR2,:CONKELDURR2,:CORPHISH,:CRAWDAUNT,:CARNIVINE,:ANORITH,:ARMALDO,:BAGON,:SHELGON,:SALAMENCE,:MUNCHLAX,:SNORLAX,:LARVESTA2,:VOLCARONA2]

#[0,1,2,3,4,5,6,7,8]
# Intentionally excludes Eternatus, Regis, Phione, Manaphy, Cresselia, Darkrai, Tapu Koko
# LevelLimit = [1,1,1,1,1,1,1,1,1] # Not being used anymore 

def pbStartWonderTrade
 #Select Pokemon
#  lvl = LevelLimit[0] # Not being used anymore
 chosen = 0
 pbChooseTradablePokemon(1, 2,
   proc {
   |poke| !poke.egg? && !(poke.shadowPokemon?) #&& # No Eggs, No Shadow Pokemon
#   (poke.level>=lvl) # None under "lvl", no exceptions.
   })
 #Trade Pokemon
 if pbGet(1)==-1
  pbMessage(_INTL("Understandable. Have a nice day!"))
 else
  myPokemon = $player.party[pbGet(1)]
  opponent = NPCTrainer.new(RandTN[rand(RandTN.size)], :YOUNGSTER) # Just used a random trainer because I don't really care
  opponent.id = $player.make_foreign_ID
  yourPokemon = nil
  resetmoves = true
  newpoke = RandPkmn[rand(RandPkmn.size)]
  nickname = RandPN[rand(RandPN.size)]
  
  if newpoke.is_a?(Pokemon)
    newpoke.owner = Pokemon::Owner.new_from_trainer(opponent)
    yourPokemon = newpoke
    resetmoves = false
  else
    species_data = GameData::Species.try_get(newpoke)
    raise _INTL("Species does not exist ({1}).", newpoke) if !species_data
    yourPokemon = Pokemon.new(species_data.id, myPokemon.level, opponent)
  end
  yourPokemon.name          = nickname
  yourPokemon.obtain_method = 2   # traded
  yourPokemon.reset_moves if resetmoves
  yourPokemon.record_first_moves
  $player.pokedex.register(yourPokemon)
  $player.pokedex.set_owned(yourPokemon.species)
  pbFadeOutInWithMusic {
    evo = PokemonTrade_Scene.new
    evo.pbStartScreen(myPokemon,yourPokemon,$player.name,opponent.name)
    evo.pbTrade
    evo.pbEndScreen
  }
  $player.party[pbGet(1)] = yourPokemon
  pbMessage(_INTL("Enjoy your new friend!"))
 end
end
=end